service: notification-service
frameworkVersion: "3"

plugins:
  - serverless-bundle
    # serverless plugin to associate IAM role per lamda function
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 256
  region: us-east-2
  stage: ${opt:stage, 'dev'}  
  iamRoleStatements: ${file(iam/RecieveAndSendMailIAM.yml):RecieveAndSendMailIAM}

functions:
  recieveAndSendMailIAM:
    handler: src/handlers/recieveAndSendMailIAM.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1

resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(resources/MailQueue.yml):Outputs.MailQueueUrl}   

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
  bundle:
    linting: false          
